# Generated by Django 2.1.5 on 2019-04-08 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rtv',
            name='volume',
            field=models.FloatField(),
        ),
    ]
