# Generated by Django 2.1.5 on 2019-04-08 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0002_auto_20190408_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rtv',
            name='volume',
            field=models.IntegerField(),
        ),
    ]
