# Generated by Django 2.1.5 on 2019-04-08 20:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0003_auto_20190408_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lamp',
            name='intensity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='room',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sensors', to='Database.Device'),
        ),
        migrations.AlterField(
            model_name='room',
            name='humidity',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='people',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='temperature',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='rtv',
            name='volume',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
