# Generated by Django 2.1.5 on 2019-04-09 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0004_auto_20190408_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='lamp',
            name='dimmable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lamp',
            name='favourite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='favourite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rtv',
            name='favourite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lamp',
            name='state',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='people',
            field=models.BooleanField(default=False),
        ),
    ]
