# Generated by Django 2.1.5 on 2019-04-16 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0005_auto_20190409_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='door',
            name='favourite',
            field=models.BooleanField(default=False),
        ),
    ]
