# Generated by Django 2.1.5 on 2019-06-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0007_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='auto',
            field=models.BooleanField(default=False),
        ),
    ]
