# Generated by Django 2.1.7 on 2019-06-08 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0008_house_auto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='door',
            name='device',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lamp',
            name='device',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='device',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rtv',
            name='device',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
